window.App = window.App || {};

App.getTutorialPages = function() {
  return [
    // Page 1: Getting Started
    [
      '--- GETTING STARTED ---',
      '',
      'THIS IS AN APPLESOFT BASIC',
      'INTERPRETER WITH A BUILT-IN',
      'VIRTUAL FILE SYSTEM.',
      '',
      'JUST TYPE COMMANDS AT THE ]',
      'PROMPT AND PRESS ENTER.',
      '',
      'TRY TYPING:',
      '  PRINT "HELLO WORLD"',
      '',
      'YOU CAN ALSO DO MATH:',
      '  PRINT 2 + 3 * 4',
      '',
      'TYPE HELP FOR ALL COMMANDS.',
    ],
    // Page 2: Writing Programs
    [
      '--- WRITING PROGRAMS ---',
      '',
      'TO WRITE A PROGRAM, TYPE',
      'EACH LINE WITH A NUMBER:',
      '',
      '  10 HOME',
      '  20 PRINT "HI THERE!"',
      '  30 PRINT "HOW ARE YOU?"',
      '  40 END',
      '',
      'TYPE RUN TO EXECUTE IT.',
      'TYPE LIST TO SEE IT.',
      'TYPE NEW TO CLEAR IT.',
      '',
      'LINES RUN IN NUMBER ORDER.',
      'USE GAPS (10,20,30...) SO',
      'YOU CAN INSERT LINES LATER.',
    ],
    // Page 3: Variables & Input
    [
      '--- VARIABLES & INPUT ---',
      '',
      'VARIABLES STORE VALUES:',
      '  10 A = 5',
      '  20 B$ = "HELLO"',
      '  30 PRINT A',
      '  40 PRINT B$',
      '',
      'USE $ FOR TEXT VARIABLES.',
      '',
      'GET USER INPUT:',
      '  10 INPUT "NAME? ";N$',
      '  20 PRINT "HI, ";N$',
      '',
      'FOR SINGLE KEY:',
      '  10 GET A$',
      '  20 PRINT "YOU TYPED: ";A$',
    ],
    // Page 4: Loops & Conditions
    [
      '--- LOOPS & CONDITIONS ---',
      '',
      'FOR/NEXT LOOP:',
      '  10 FOR I = 1 TO 10',
      '  20 PRINT I;" ";',
      '  30 NEXT I',
      '',
      'IF/THEN:',
      '  10 INPUT "NUMBER? ";N',
      '  20 IF N > 5 THEN PRINT "BIG"',
      '  30 IF N <= 5 THEN PRINT "SMALL"',
      '',
      'GOTO (JUMP TO LINE):',
      '  10 PRINT "LOOP!"',
      '  20 GOTO 10',
      '',
      'CTRL+C TO STOP A LOOP!',
    ],
    // Page 5: Subroutines
    [
      '--- SUBROUTINES ---',
      '',
      'GOSUB CALLS A SUBROUTINE,',
      'RETURN COMES BACK:',
      '',
      '  10 PRINT "START"',
      '  20 GOSUB 100',
      '  30 PRINT "BACK"',
      '  40 END',
      '  100 PRINT "IN SUBROUTINE"',
      '  110 RETURN',
      '',
      'USE ON..GOTO FOR MENUS:',
      '  10 INPUT "CHOICE(1-3)? ";C',
      '  20 ON C GOTO 100,200,300',
    ],
    // Page 6: String Functions
    [
      '--- STRING FUNCTIONS ---',
      '',
      'LEN(A$)      STRING LENGTH',
      'LEFT$(A$,N)  LEFT N CHARS',
      'RIGHT$(A$,N) RIGHT N CHARS',
      'MID$(A$,S,N) MIDDLE CHARS',
      'ASC(A$)      ASCII CODE',
      'CHR$(N)      CODE TO CHAR',
      'VAL(A$)      STRING TO NUM',
      'STR$(N)      NUM TO STRING',
      '',
      'EXAMPLE:',
      '  10 A$ = "HELLO WORLD"',
      '  20 PRINT LEN(A$)',
      '  30 PRINT LEFT$(A$,5)',
      '  40 PRINT MID$(A$,7,5)',
    ],
    // Page 7: Math Functions
    [
      '--- MATH FUNCTIONS ---',
      '',
      'INT(X)  INTEGER PART',
      'ABS(X)  ABSOLUTE VALUE',
      'SGN(X)  SIGN (-1,0,1)',
      'SQR(X)  SQUARE ROOT',
      'RND(X)  RANDOM (0-1)',
      'SIN(X)  SINE',
      'COS(X)  COSINE',
      'TAN(X)  TANGENT',
      'ATN(X)  ARCTANGENT',
      'EXP(X)  E TO THE X',
      'LOG(X)  NATURAL LOG',
      '',
      'RANDOM NUMBER 1-6:',
      '  PRINT INT(RND(1)*6)+1',
    ],
    // Page 8: Graphics
    [
      '--- LO-RES GRAPHICS ---',
      '',
      'GR          GRAPHICS MODE',
      'COLOR= N    SET COLOR (0-15)',
      'PLOT X,Y    DRAW PIXEL',
      'HLIN X1,X2 AT Y  HORIZ LINE',
      'VLIN Y1,Y2 AT X  VERT LINE',
      'TEXT        BACK TO TEXT',
      '',
      'EXAMPLE:',
      '  10 GR',
      '  20 COLOR= 1',
      '  30 FOR X = 0 TO 39',
      '  40 PLOT X,20',
      '  50 NEXT X',
      '  60 GET A$ : TEXT',
    ],
    // Page 9: File System
    [
      '--- FILE SYSTEM ---',
      '',
      'YOUR VIRTUAL DISK:',
      '  CATALOG    LIST FILES',
      '  CD "DIR"   CHANGE DIR',
      '  MKDIR "X"  NEW FOLDER',
      '  RMDIR "X"  DEL FOLDER',
      '  PWD        CURRENT DIR',
      '',
      'FILE COMMANDS:',
      '  SAVE "X"   SAVE PROGRAM',
      '  LOAD "X"   LOAD PROGRAM',
      '  TYPE "X"   VIEW FILE',
      '  DELETE "X"  DELETE FILE',
      '  CREATE "X"  NEW FILE',
      '  RENAME "A","B"  RENAME',
    ],
    // Page 10: Upload/Download & Samples
    [
      '--- UPLOAD & DOWNLOAD ---',
      '',
      'UPLOAD FILES FROM YOUR PC:',
      '  UPLOAD',
      '  (OPENS FILE DIALOG)',
      '',
      'DOWNLOAD FILES TO YOUR PC:',
      '  DOWNLOAD       (PROGRAM)',
      '  DOWNLOAD "X"   (FILE)',
      '',
      '--- SAMPLE PROGRAMS ---',
      '',
      'SAMPLE PROGRAMS ARE IN THE',
      '/SAMPLES DIRECTORY:',
      '  CD "SAMPLES"',
      '  CATALOG',
      '  LOAD "HELLO"',
      '  RUN',
    ],
  ];
};
